/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SupplierManagment;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DIAS-PC
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        Connect();
        Supplier();
        load();
        Image icon = new ImageIcon(this.getClass().getResource("/Icon.png")).getImage();
       this.setIconImage(icon);
    }
    
    
    
    Connection con;
    PreparedStatement pst;
    DefaultTableModel df;
    ResultSet rs;

    public void Connect() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/company", "root", "");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    
     private void Supplier() {

        try {
            pst = con.prepareStatement("select Distinct Sup_Name from supplier");
            rs = pst.executeQuery();

            com_sup_name.removeAllItems();

            while (rs.next()) {

                com_sup_name.addItem(rs.getString("Sup_Name"));
                com_sup_name.setSelectedItem("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }

    } 
    
    
     
     
     
     
     
     public void load(){
        
        int a;
        
        try {
            pst=con.prepareStatement("select*from product");
            ResultSet rs=pst.executeQuery();
            
            ResultSetMetaData rd=rs.getMetaData();
            a = rd.getColumnCount();
            df =(DefaultTableModel)Product_table.getModel();
            df.setRowCount(0);
            
            while(rs.next()){
                
                Vector v2 = new Vector();
                for(int i=1; i<=a; i++ ){
                    
                    v2.add(rs.getString("Pro_Code"));
                    v2.add(rs.getString("Pro_Name"));
                    v2.add(rs.getString("Sup_Name"));
                    v2.add(rs.getString("Cost_Price"));
                    
                    
                    
                }
                df.addRow(v2);
            }
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     } 
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Pro_name = new javax.swing.JTextField();
        txt_Pro_CP = new javax.swing.JTextField();
        com_sup_name = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Pro_Name = new javax.swing.JLabel();
        Pro_Cost = new javax.swing.JLabel();
        Pro_Com = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        bnt_edit = new javax.swing.JButton();
        btn_delete6 = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        btn_clear6 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Product_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Product Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Supplier Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Cost Price");

        txt_Pro_name.setBackground(new java.awt.Color(204, 204, 204));
        txt_Pro_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Pro_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Pro_nameKeyReleased(evt);
            }
        });

        txt_Pro_CP.setBackground(new java.awt.Color(204, 204, 204));
        txt_Pro_CP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Pro_CP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Pro_CPKeyReleased(evt);
            }
        });

        com_sup_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIAS-PC\\Downloads\\8915355271557740322-128.png")); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Product Information");

        Pro_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pro_Name.setForeground(new java.awt.Color(255, 51, 0));

        Pro_Cost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pro_Cost.setForeground(new java.awt.Color(255, 51, 0));

        Pro_Com.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pro_Com.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(204, 204, 204))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Pro_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(com_sup_name, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Pro_CP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(183, 183, 183))
                            .addComponent(Pro_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pro_Com, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pro_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Pro_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(com_sup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro_Com, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Pro_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pro_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        btn_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        bnt_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_edit.setText("Edit");
        bnt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_editActionPerformed(evt);
            }
        });

        btn_delete6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_delete6.setText("Delete");
        btn_delete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete6ActionPerformed(evt);
            }
        });

        btn_report.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_report.setText("Report");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });

        btn_clear6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clear6.setText("Clear");
        btn_clear6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_report, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btn_clear6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btn_delete6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnt_edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        Product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Supplier Name", "Cost Price"
            }
        ));
        Product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Product_table);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIAS-PC\\Downloads\\5020973501543238905-32.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if(txt_Pro_name.getText().trim().isEmpty()){
            
            Pro_Name.setText("Product Name is Empty");
            
        }else if(txt_Pro_CP.getText().trim().isEmpty()){
            
            Pro_Cost.setText("Cost Price is Empty");
            
        }else 
        
      try {
            
                
                String Pro_Name =txt_Pro_name.getText();
                String Sup_Name=com_sup_name.getSelectedItem().toString();
                String Cost_Price =txt_Pro_CP.getText();
                
            
            
            
            // TODO add your handling code here:

            pst= con.prepareStatement("insert into product(Pro_Name,Sup_Name,Cost_Price)values(?,?,?)");
            
           
            pst.setString(1, Pro_Name);
            pst.setString(2, Sup_Name);
            pst.setString(3, Cost_Price);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Product Data Add Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
            
            txt_Pro_name.setText("");
            
            txt_Pro_CP.setText("");
            
            
            load();
            
           
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Product Data Can Not Add","Error",JOptionPane.ERROR_MESSAGE);
        }
               
               
               
               
               
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void Product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = Product_table.getSelectedRow();
        
        df = (DefaultTableModel)Product_table.getModel();
        int selected = Product_table.getSelectedRow();
        
        
        
        txt_Pro_name.setText(df.getValueAt(selected,1).toString());
        
        String comboSub = df.getValueAt(selectedRow, 2).toString();
        for (int i = 0; i < com_sup_name.getItemCount(); i++) {
            if (com_sup_name.getItemAt(i).toString().equalsIgnoreCase(comboSub)) {
                com_sup_name.setSelectedIndex(i);
            }
        }
        
        
        txt_Pro_CP.setText(df.getValueAt(selected,3).toString());
        int Pro_Code = Integer.parseInt(df.getValueAt(selected,0).toString());
        
        btn_add.setEnabled(false);
        
        
        
        
        
    }//GEN-LAST:event_Product_tableMouseClicked

    private void bnt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_editActionPerformed
        // TODO add your handling code here:
        
      
        df = (DefaultTableModel)Product_table.getModel();
        int selected = Product_table.getSelectedRow();
        
        int Pro_Code = Integer.parseInt(df.getValueAt(selected,0).toString());
        
                String Pro_Name =txt_Pro_name.getText();
                String Sup_Name=com_sup_name.getSelectedItem().toString();
                String Cost_Price =txt_Pro_CP.getText();
        
            
        try {
            // TODO add your handling code here:

            pst= con.prepareStatement("update product set Pro_Name=?,Sup_Name=?,Cost_Price=? where Pro_Code=? ");
            
            pst.setString(1, Pro_Name);
            pst.setString(2, Sup_Name);
            pst.setString(3, Cost_Price);
            pst.setInt(4, Pro_Code);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Product Data Updated Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
            
            txt_Pro_name.setText("");
            txt_Pro_CP.setText("");
            
            txt_Pro_name.requestFocus();
            load();
            btn_add.setEnabled(true);
            
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,"Product Data Can Not Update","Error",JOptionPane.ERROR_MESSAGE);
        }
            
           
        
        
        
        
    }//GEN-LAST:event_bnt_editActionPerformed

    private void btn_delete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete6ActionPerformed
        // TODO add your handling code here:
        
        df = (DefaultTableModel)Product_table.getModel();
        int selected = Product_table.getSelectedRow();
        
        int Pro_Code = Integer.parseInt(df.getValueAt(selected,0).toString());
        
        
                
            
            
            
        try {
            // TODO add your handling code here:

            pst= con.prepareStatement("delete from product where Pro_Code = ?");
            
            
            pst.setInt(1, Pro_Code);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Product Data Delete Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
            
            txt_Pro_name.setText("");
            txt_Pro_CP.setText("");
            txt_Pro_name.requestFocus();
            load();
            btn_add.setEnabled(true);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Product Data Can Not Delete","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_delete6ActionPerformed

    private void btn_clear6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear6ActionPerformed
        // TODO add your handling code here:
        
        
        txt_Pro_name.setText(""); 
        txt_Pro_CP.setText(""); 
         load();
         btn_add.setEnabled(true);
        
        
        
    }//GEN-LAST:event_btn_clear6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setExtendedState(Product.ICONIFIED);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:

        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        // TODO add your handling code here:
        
         try{
            InputStream in= new FileInputStream(new File("D:\\CODSE201F-016\\SupplierManagment\\src\\SupplierManagment\\Product.jrxml"));
            JasperDesign jd=JRXmlLoader.load(in);
            String sql="select*from product";
            JRDesignQuery newQuery= new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr=JasperCompileManager.compileReport(jd);
            HashMap para=new HashMap();
            JasperPrint j = JasperFillManager.fillReport(jr, para,con);
            JasperViewer.viewReport(j,false);
            
     
         
     }catch(Exception e){
         
         JOptionPane.showMessageDialog(null, e);
     }
        
    }//GEN-LAST:event_btn_reportActionPerformed

    private void txt_Pro_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Pro_nameKeyReleased
        // TODO add your handling code here:
        
        Pro_Name.setText("");
        
    }//GEN-LAST:event_txt_Pro_nameKeyReleased

    private void txt_Pro_CPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Pro_CPKeyReleased
        // TODO add your handling code here:
        
        Pro_Cost.setText("");
        
        String Cost_Price = txt_Pro_CP.getText();
        if(Cost_Price.matches("^\\d{0,8}(\\.\\d{1,4})?$")){
            
            txt_Pro_CP.setBackground(Color.green);
            
        } else {
            
            txt_Pro_CP.setBackground(new Color(255,102,102));
            Pro_Cost.setText("Incorect Format");
        }
        
    }//GEN-LAST:event_txt_Pro_CPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pro_Com;
    private javax.swing.JLabel Pro_Cost;
    private javax.swing.JLabel Pro_Name;
    private javax.swing.JTable Product_table;
    private javax.swing.JButton bnt_edit;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear6;
    private javax.swing.JButton btn_delete6;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_report;
    private javax.swing.JComboBox<String> com_sup_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Pro_CP;
    private javax.swing.JTextField txt_Pro_name;
    // End of variables declaration//GEN-END:variables
}
